calmato/presto-pay

native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/res/drawable/circle_theme_color.xml, native/android/app/src/main/res/drawable/circle_white.xml, native/android/app/src/main/res/drawable/ic_add_black_50dp.xml, native/android/app/src/main/res/drawable/ic_people_black_24dp.xml, native/android/app/src/main/res/drawable/ic_person_black_24dp.xml, native/android/app/src/main/res/layout/fooder.xml, native/android/app/src/main/res/values/strings.xml
=> エラーの修正。フッダーの作成。

api/user/bin/build-mocks.sh, api/user/internal/application/request/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/base.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/user/entity.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/domain/validation.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/infrastructure/validation/user_test.go, api/user/lib/firebase/authentication/client.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: Create Authentication

api/user/config/router.go, api/user/internal/application/response/error.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/user.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/error.go, api/user/internal/domain/user/entity.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/domain/validation.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/infrastructure/validation/user.go, api/user/internal/infrastructure/validation/user_test.go, api/user/internal/interface/handler/error.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: ユーザー編集APIの実装

api/user/config/router.go, api/user/internal/application/request/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/user.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: ユーザーパスワード編集APIの実装

native/ios/.gitignore, native/ios/PrestoPay.xcodeproj/project.pbxproj, native/ios/PrestoPay.xcodeproj/project.xcworkspace/contents.xcworkspacedata, native/ios/PrestoPay.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, native/ios/PrestoPay/AppDelegate.swift, native/ios/PrestoPay/Assets.xcassets/AppIcon.appiconset/Contents.json, native/ios/PrestoPay/Assets.xcassets/Contents.json, native/ios/PrestoPay/Base.lproj/LaunchScreen.storyboard, native/ios/PrestoPay/Info.plist, native/ios/PrestoPay/PrestoPay.xcdatamodeld/.xccurrentversion, native/ios/PrestoPay/PrestoPay.xcdatamodeld/PrestoPay.xcdatamodel/contents, native/ios/PrestoPay/Preview Content/Preview Assets.xcassets/Contents.json, native/ios/PrestoPay/SceneDelegate.swift, native/ios/PrestoPay/Views/ContentView.swift
=> setup swift app

native/ios/PrestoPay/Views/LoginView.swift, native/ios/PrestoPay/Views/SignUpView.swift
=> fix: login page 

native/ios/PrestoPay/ViewModels/Auth/LoginViewModel.swift, native/ios/PrestoPay/ViewModels/Auth/SIgnUpViewModel.swift
=> feat: Create SignUpViewModel

infra/terraform/modules/gke-node.tf
=> feat: Update terraform

.github/workflows/ci-terraform.yaml
=> feat: Create workflow for terraform

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/MainActivity.kt, native/android/app/src/main/java/work/calmato/prestopay/login/CreateNewAccount.kt, native/android/app/src/main/java/work/calmato/prestopay/login/RestClient.kt, native/android/app/src/main/res/layout/fragment_login.xml, native/android/app/src/main/res/values/strings.xml, native/android/app/src/main/res/xml/network_security_config.xml
APIを叩いてアカウント作成をできるようにした。
コード汚いけど、とりあえず動くか確認。
=> アカウント作成の実装

native/android/app/build.gradle
=> firebaseのversionを変更

native/android/.gitignore
=> git ignoreの編集

.github/workflows/ci-android.yaml, .idea/codeStyles/Project.xml, .idea/misc.xml, .idea/modules.xml, .idea/presto-pay.iml, .idea/vcs.xml, .idea/workspace.xml
=> Revert "Revert "Feature/android setting""

.github/workflows/ci-android.yaml, native/android/app/src/main/java/work/calmato/prestopay/MainActivity.kt
=> restore branch

docker-compose.yaml, infra/docker/grafana/Dockerfile_development, infra/docker/prometheus/Dockerfile_development, infra/prometheus/development.yaml
=> feat: Create monitoring containers

infra/docker/api/calc/Dockerfile
=> feat: Create Dockerfile for staging

api/calc/internal/domain/user/entity.go, api/calc/internal/domain/user/service.go
=> feat: Create user domain

.github/workflows/cd-user-api.yaml, api/user/config/router.go, api/user/internal/application/request/user.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/user.go, api/user/internal/application/validation/user_test.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, infra/kubernetes/Makefile
* ログインユーザー情報取得APIの実装
* user-apiのCD編集
=> feat: ログインユーザ情報取得APIの実装

api/calc/cmd/main.go, api/calc/config/environment.go, api/calc/config/router.go, api/calc/go.mod, api/calc/go.sum, api/calc/internal/application/group.go, api/calc/internal/application/request/group.go, api/calc/internal/domain/error.go, api/calc/internal/domain/group/entity.go, api/calc/internal/domain/user/entity.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/user.go, api/calc/internal/interface/handler/v1/group.go, api/calc/registry/group.go, api/calc/registry/registry.go, api/user/internal/infrastructure/repository/user.go
=> Feature/calc cpi/create group

native/android/app/src/main/res/drawable/clear_button_bg.xml, native/android/app/src/main/res/layout/fragment_account_home.xml, native/android/app/src/main/res/values/colors.xml
=> 各種設定のUIホームの実装

api/calc/go.mod, api/calc/internal/application/group.go, api/calc/internal/application/request/group.go, api/calc/internal/application/validation/base.go, api/calc/internal/application/validation/group.go, api/calc/internal/domain/group/repository.go, api/calc/internal/domain/group/service.go, api/calc/internal/domain/group/uploader.go, api/calc/internal/domain/group/validation.go, api/calc/internal/infrastructure/repository/context.go, api/calc/internal/infrastructure/repository/group.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/storage/context.go, api/calc/internal/infrastructure/storage/group.go, api/calc/internal/infrastructure/validation/group.go, api/calc/registry/group.go, api/user/internal/infrastructure/repository/user.go
* wip) グループ作成APIの実装
* UserIDを用いて、ユーザー追加を同時にできるように
=> feat: [WIP] グループ作成APIの実装

api/user/config/router.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/domain/user/entity.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/infrastructure/validation/user.go, api/user/internal/infrastructure/validation/user_test.go, api/user/internal/interface/handler/v1/user.go, api/user/lib/common/remove.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go
=> feature: サービス間通信用のUser APIエンドポイントの作成

api/calc/internal/infrastructure/api/client.go
=> fix: PATHの修正

api/user/internal/interface/handler/v1/user.go, docs/12_backend/21_swagger/apiv1.yaml
* ユーザー情報取得時、グループID一覧が取得できるように
* swaggerのtypo修正
=> feature: ユーザー情報取得時のレスポンスを更新

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/res/layout/fragment_login.xml, native/android/app/src/main/res/values/strings.xml, native/android/build.gradle
=> [ADD] facebookを用いたsign in

native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/res/values/strings.xml
=> [FIX]Facebook の共通アカウントに変更

api/user/internal/interface/handler/v1/user.go, api/user/lib/firebase/firestore/client.go, docs/12_backend/21_swagger/apiv1.yaml, infra/envoy/development.yaml, infra/kubernetes/stg/default/ingress.yaml
* ユーザー検索APIの修正
* swaggerの更新
* k8s, envoyのconfig変更
* firestore? NoSQL? の使用上、前方一致検索しかできない...
* -> like検索みたいなの必要であれば、RDBへの切替検討
=> feature: ユーザー検索APIの実装

api/user/config/router.go, docs/12_backend/21_swagger/apiv1.yaml
=> feat: Update endpoint

api/user/internal/domain/user/entity.go, api/user/internal/infrastructure/service/user.go, api/user/lib/firebase/authentication/client.go
=> ユーザーエンティティにカラムの追加

api/user/internal/infrastructure/repository/user.go
=> feat: Update user repository

api/user/config/router.go, docs/12_backend/21_swagger/apiv1.yaml, native/android/app/src/main/java/work/calmato/prestopay/ui/newAccount/NewAccountFragment.kt
=> refactor: ユーザー登録のエンドポイント編集

native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/mailCheck/MailCheckFragment.kt, native/android/app/src/main/res/navigation/navigation.xml
-グループ作成のバリデーション
- メールチェック画面で戻るボタンを押すとホーム画面に戻れるようにした
=> グループ作成のバリデーション

api/user/config/router.go, api/user/internal/application/request/user.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/user.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/user/entity.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/infrastructure/validation/user.go, api/user/internal/infrastructure/validation/user_test.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 友達追加APIの実装

api/user/internal/application/user.go, api/user/internal/application/user_test.go
=> fix: add friend

api/user/config/router.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/service/user_test.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 友達一覧取得APIの実装

api/user/config/router.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/interface/handler/v1/user.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 友達削除APIの実装

api/user/config/router.go
=> fix: 友達削除APIのPATHを修正

api/user/internal/interface/handler/v1/user.go
=> fix: Assign to array

api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/group_test.go, api/calc/internal/application/response/group.go, api/calc/internal/domain/group/entity.go, api/calc/internal/domain/group/service.go, api/calc/internal/domain/user/entity.go, api/calc/internal/domain/user/service.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/service/group_test.go, api/calc/internal/infrastructure/service/user.go, api/calc/internal/infrastructure/service/user_test.go, api/calc/internal/interface/handler/v1/group.go, api/calc/mock/domain/group/service.go, api/calc/mock/domain/user/service.go, docs/12_backend/21_swagger/apiv1.yaml
* グループ一覧取得APIの実装
* グループ詳細取得APIの実装
=> feature: グループ一覧・詳細取得APIの実装

native/android/app/src/main/java/work/calmato/prestopay/ui/addFriend/AddFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterRecyclePlane.kt
=> Adapter間違ってたので修正！

native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/accountEdit/AccountEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/accountHome/AccountHomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/home/HomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/mailCheck/MailCheckFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/notificationSet/NotificationSetFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPassLogin/UpdatePassLoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt, native/android/app/src/main/res/layout/fragment_account_edit.xml, native/android/app/src/main/res/layout/fragment_account_home.xml, native/android/app/src/main/res/layout/fragment_group_friend.xml, native/android/app/src/main/res/layout/fragment_notification_set.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/navigation/navigation.xml
=> Feature database

api/calc/internal/application/request/payment.go, api/calc/internal/application/response/payment.go, api/calc/internal/domain/payment/entity.go, api/calc/internal/interface/handler/v1/payment.go
=> fix: payment entity

native/android/app/src/main/java/work/calmato/prestopay/database/DatabaseFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterGroupPlane.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt
=> うごくようになった！

api/calc/internal/application/request/payment.go, api/calc/internal/application/response/payment.go, api/calc/internal/domain/payment/entity.go
=> refactor: Update payment arguments

api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/group_test.go, api/calc/internal/application/request/group.go, api/calc/internal/application/response/group.go, api/calc/internal/application/validation/group.go, api/calc/internal/application/validation/group_test.go, api/calc/internal/domain/group/repository.go, api/calc/internal/domain/group/service.go, api/calc/internal/infrastructure/repository/group.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/service/group_test.go, api/calc/internal/interface/handler/v1/group.go, api/calc/mock/application/validation/group.go, api/calc/mock/domain/group/repository.go, api/calc/mock/domain/group/service.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: グループへユーザー追加用APIの実装

.github/workflows/ci-admin.yaml, .github/workflows/ci-android-on-master-branch.yaml, .github/workflows/ci-android.yaml, .github/workflows/ci-calc-api-reviewdog.yaml, .github/workflows/ci-calc-api.yaml, .github/workflows/ci-terraform.yaml, .github/workflows/ci-user-api-reviewdog.yaml, .github/workflows/ci-user-api.yaml
=> feature: Github Actionsの定義ファイルの更新

infra/terraform/env/stg/main.tf
* g1-small -> e2-micro && e2-small
* 1.15.11-gke.13 -> 1.16.13-gke.1
=> feature: 開発環境のノードタイプ変更

infra/terraform/env/stg/main.tf
=> feat: Add node

api/user/config/router.go, api/user/go.mod, api/user/go.sum, api/user/internal/application/request/user.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/application/validation/user.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/user/entity.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, docs/12_backend/21_swagger/apiv1.yaml, docs/12_backend/21_swagger/internal.yaml
=> feature: デバイスID登録用APIの実装

api/calc/go.sum
=> chore: go mod tidy in calc api

infra/kubernetes/stg/monitoring/daemonset-node-exporter.yaml, infra/kubernetes/stg/monitoring/deployment-fluentd.yaml, infra/kubernetes/stg/monitoring/deployment-grafana.yaml, infra/kubernetes/stg/monitoring/deployment-kube-state-metrics.yaml, infra/kubernetes/stg/monitoring/deployment-loki.yaml, infra/kubernetes/stg/monitoring/deployment-prometheus.yaml
=> feature: モニタリングのPodをスケールアップ

native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/layout/spinner_item_currency.xml
=> Feature view model friend

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/ui/accountEdit/AccountEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/newAccount/NewAccountFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/PermissionBase.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/layout/spinner_item_currency.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/build.gradle
=> Feature crop image

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/ui/accountEdit/AccountEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addFriend/AddFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/newAccount/NewAccountFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPass/ResetPassFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPassLogin/UpdatePassLoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/InternetConnectionUI.kt, native/android/app/src/main/java/work/calmato/prestopay/util/PermissionBase.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/res/layout/fragment_account_edit.xml, native/android/app/src/main/res/layout/fragment_add_expense.xml, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_login.xml, native/android/app/src/main/res/layout/fragment_new_account.xml, native/android/app/src/main/res/layout/fragment_reset_pass.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/layout/spinner_item_currency.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml, native/android/build.gradle
- 通信系のボタンをダブルクリックできないようにした
- 通信中はNow Loadingというテキストを点滅させるようにした
=> Feature unable double click

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/ui/accountEdit/AccountEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addFriend/AddFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/newAccount/NewAccountFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPass/ResetPassFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPassLogin/UpdatePassLoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/InternetConnectionUI.kt, native/android/app/src/main/java/work/calmato/prestopay/util/PermissionBase.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/res/layout/fragment_account_edit.xml, native/android/app/src/main/res/layout/fragment_add_expense.xml, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_login.xml, native/android/app/src/main/res/layout/fragment_new_account.xml, native/android/app/src/main/res/layout/fragment_reset_pass.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/layout/spinner_item_currency.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml, native/android/build.gradle
=> Feature twitter login

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/ui/accountEdit/AccountEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addFriend/AddFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/newAccount/NewAccountFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPass/ResetPassFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/resetPassLogin/UpdatePassLoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/InternetConnectionUI.kt, native/android/app/src/main/java/work/calmato/prestopay/util/PermissionBase.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/res/layout/fragment_account_edit.xml, native/android/app/src/main/res/layout/fragment_add_expense.xml, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_login.xml, native/android/app/src/main/res/layout/fragment_new_account.xml, native/android/app/src/main/res/layout/fragment_reset_pass.xml, native/android/app/src/main/res/layout/fragment_update_pass_login.xml, native/android/app/src/main/res/layout/spinner_item_currency.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml, native/android/build.gradle
=> Feature android

native/android/app/build.gradle, native/android/app/src/main/AndroidManifest.xml, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/MyFirebaseMessagingService.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelUser.kt
=> feature: FCM用のデバイスID送信処理追加

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/FriendsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupList/GroupListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/home/HomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterGroupPlane.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelGroup.kt, native/android/app/src/main/res/navigation/navigation.xml
=> Feature android group

api/calc/cmd/main.go, api/calc/go.mod, api/calc/go.sum, api/calc/lib/firebase/authentication/client.go, api/calc/lib/firebase/client.go, api/calc/lib/firebase/firestore/client.go, api/calc/lib/firebase/messaging/client.go, api/calc/lib/firebase/storage/client.go, api/calc/registry/registry.go
* Firebase Cloud Messagingを操作用ライブラリの作成
=> feature: Firebase Cloud Messagingを操作用ライブラリの作成

api/calc/internal/domain/user/entity.go, api/calc/internal/infrastructure/service/payment.go, api/calc/registry/payment.go, api/calc/registry/registry.go, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt
=> feat: Update payment service

api/calc/internal/infrastructure/service/payment.go, api/calc/lib/firebase/messaging/client.go
=> feat: Add notification in register payment

native/react/src/@types/image.d.ts
=> feat: setup directories

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/FriendsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/GroupsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/accountHome/AccountHomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelUser.kt
=> Feature fcm fix

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/FriendsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/GroupsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/accountHome/AccountHomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt
=> Feature android logout

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/FriendsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/GroupsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt
- グループとフレンド一覧を取得した際に一度データベースを消去することで、ローカルのデータベースをファイヤーベース上のデータベースと同期できるようにした
=> Feature database refresh

native/react/src/components/atoms/TextField/index.tsx, native/react/src/components/atoms/index.ts, native/react/src/components/pages/SignIn/index.tsx, native/react/src/lib/hooks/index.ts, native/react/src/lib/hooks/use-controlled-component.ts
=> feat: [WIP] update ui

native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/res/layout/fragment_add_expense.xml
=> 支払い登録できるようにした

.github/workflows/ci-native.yaml, native/react/package.json, native/react/src/components/atoms/Button/index.tsx, native/react/src/components/atoms/TextField/index.tsx, native/react/src/components/pages/SignIn/index.tsx, native/react/src/contexts/ui.ts, native/react/src/routes/Main/index.tsx, native/react/yarn.lock
* ログイン画面のUI実装
* OAuth認証ボタンのアイコン追加
* コンポーネントへの分割
=> feature: ログイン画面のUI実装

api/calc/config/router.go, api/calc/internal/application/payment.go, api/calc/internal/application/response/payment.go, api/calc/internal/domain/payment/entity.go, api/calc/internal/domain/payment/repository.go, api/calc/internal/domain/payment/service.go, api/calc/internal/infrastructure/repository/payment.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/infrastructure/service/payment_test.go, api/calc/internal/interface/handler/v1/payment.go, api/calc/lib/firebase/firestore/client.go, api/calc/mock/domain/payment/repository.go, api/calc/mock/domain/payment/service.go, api/calc/registry/payment.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 支払い情報一覧取得APIの実装

api/calc/internal/application/payment.go, api/calc/internal/domain/payment/repository.go, api/calc/internal/domain/payment/service.go, api/calc/internal/infrastructure/repository/payment.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/interface/handler/v1/payment.go, api/calc/lib/firebase/firestore/client.go, api/calc/mock/domain/payment/repository.go, api/calc/mock/domain/payment/service.go, api/user/internal/infrastructure/repository/user.go, api/user/lib/firebase/firestore/client.go, docs/12_backend/21_swagger/apiv1.yaml
=> refactor: firestore libraries

native/android/app/src/main/java/work/calmato/prestopay/repository/GroupsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addFriend/AddFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/createGroup/CreateGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupList/GroupListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/home/HomeFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/login/LoginFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelGroup.kt, native/android/app/src/main/res/layout/fragment_friend_list.xml, native/android/app/src/main/res/layout/fragment_group_friend.xml, native/android/app/src/main/res/layout/fragment_group_list.xml, native/android/app/src/main/res/layout/fragment_home.xml, native/android/app/src/main/res/navigation/navigation.xml
- アプリ立ち上げたときにグループと友達の情報更新するようにした
- 各リサイクラービューでスワイプで更新できるようにした
=> Feature android network

native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupEdit/GroupEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/res/layout/fragment_group_edit.xml, native/android/app/src/main/res/layout/fragment_group_friend.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values/strings.xml
- group編集画面を実装した
ここ @Atsuhide と同じところ変更して、もしかしたらconflict 起こすかも！
pull してからmergeするか、git hub上でconflictを解決してくれ笑
=> group 編集画面の実装

api/calc/.golangci.yaml, api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/request/group.go, api/calc/internal/application/response/group.go, api/calc/internal/application/validation/group.go, api/calc/internal/domain/group/service.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/interface/handler/v1/group.go, api/calc/lib/common/remove.go, api/calc/mock/application/validation/group.go, api/calc/mock/domain/group/service.go, docs/12_backend/21_swagger/apiv1.yaml
* グループ編集APIの実装
* グループへユーザ追加APIの編集
* グループからユーザ削除APIの実装
=> feature: グループ編集APIの実装

api/calc/internal/infrastructure/service/group.go
=> fix: グループ編集APIの修正

api/calc/config/router.go, api/calc/internal/application/payment.go, api/calc/internal/application/request/payment.go, api/calc/internal/application/response/group.go, api/calc/internal/application/response/payment.go, api/calc/internal/application/validation/payment.go, api/calc/internal/domain/payment/repository.go, api/calc/internal/domain/payment/service.go, api/calc/internal/infrastructure/repository/payment.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/interface/handler/v1/payment.go, api/calc/lib/firebase/firestore/client.go, api/calc/mock/application/validation/payment.go, api/calc/mock/domain/payment/repository.go, api/calc/mock/domain/payment/service.go, api/user/lib/firebase/firestore/client.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 支払い情報更新APIの実装

api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/payment.go, api/calc/internal/domain/group/repository.go, api/calc/internal/domain/group/service.go, api/calc/internal/domain/payment/repository.go, api/calc/internal/domain/payment/service.go, api/calc/internal/infrastructure/repository/group.go, api/calc/internal/infrastructure/repository/payment.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/interface/handler/v1/group.go, api/calc/internal/interface/handler/v1/payment.go, api/calc/mock/domain/group/repository.go, api/calc/mock/domain/group/service.go, api/calc/mock/domain/payment/repository.go, api/calc/mock/domain/payment/service.go, docs/12_backend/21_swagger/apiv1.yaml
* グループ削除APIの実装
* 支払い情報削除APIの実装
=> feature: 削除関連のAPI実装

api/calc/internal/application/response/payment.go, api/calc/internal/domain/payment/entity.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/interface/handler/v1/payment.go, docs/12_backend/21_swagger/apiv1.yaml
* 支払い情報関連の各レスポンスに `groupId` を追加
* LINE内での依頼内容があってるか、コメントの内容を確認してほしい
=> feature: 支払い情報関連のレスポンスを編集

native/react/package.json, native/react/src/components/molecules/HomeSwipeListHiddenItem/index.tsx, native/react/src/components/molecules/HomeSwipeListItem/index.tsx, native/react/src/components/molecules/SearchBar/index.tsx, native/react/src/components/molecules/TotalAmountViewer/index.tsx, native/react/src/components/organisms/HomeSwipeList/index.tsx, native/react/src/components/pages/Home/index.tsx, native/react/yarn.lock
- 検索バーの部分のUI作成
- 貸付金額の合計を表示する部分のUI作成
- react-native-swipe-list-viewを導入してスワイプできるリストのUI作成
- 色の指定
- margin, paddingの当ててる部分とか
- クリックされた時の挙動
=> Home画面のリスト部分のUIを作成

native/react/src/constants/theme.ts, native/react/src/routes/Main/Group/GroupList.tsx, native/react/src/routes/Main/Home.tsx, native/react/src/routes/Main/System/UserInfo.tsx, native/react/src/routes/Main/index.tsx
- タブナビゲーションにアイコンをつけた．
- ヘッダーの色を変更した．
- アイコンや色の設定など
- タブナビゲーションとヘッダーの文字の変更
=> ヘッダーとタブナビゲーションのUI作成

native/react/src/components/pages/Initial/index.tsx, native/react/src/components/pages/Loading/index.tsx, native/react/src/components/pages/UserInfo/index.tsx, native/react/src/containers/Loading.tsx, native/react/src/containers/UserInfo.tsx, native/react/src/containers/index.ts, native/react/src/lib/firebase/index.ts, native/react/src/lib/firebase/sign-out.ts, native/react/src/lib/local-storage/initial-launch.ts, native/react/src/modules/auth.ts, native/react/src/routes/Main/Auth/CheckEmail.tsx, native/react/src/routes/Main/Auth/PasswordReset.tsx, native/react/src/routes/Main/Auth/SignUp.tsx, native/react/src/routes/Main/System/UserInfo.tsx, native/react/src/routes/Main/index.tsx, native/react/src/usecases/auth.ts
* サインアウト機能の実装
* 初回起動ローディング機能の実装
=> feature: サインアウト機能の実装

native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/friendList/FriendListFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupEdit/GroupEditFragment.kt, native/android/app/src/main/res/layout/fragment_group_edit.xml, native/android/app/src/main/res/navigation/navigation.xml
group編集の実装
Thumnailの取得がおそらく、タイミングの問題で失敗しているのでToastにerrorと出るが処理的にはできている。
しかし、このままだとまずいので対処する。 同期処理にすれば解決？
=> Group edit

native/android/app/src/main/java/work/calmato/prestopay/database/DatabaseFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/BindingUtils.kt
=> thumnailのエラーの修正

docs/11_frontend/01_native/13_react_native/README.md, docs/11_frontend/01_native/13_react_native/command.md, docs/11_frontend/01_native/13_react_native/directories.md, docs/11_frontend/01_native/13_react_native/libraries.md
* React Native関連のドキュメント追加
* 過不足あったら編集よろしく!!
=> docs: React Native関連のドキュメント追加

docker-compose.api.yaml, docker-compose.yaml, infra/docker/api/batch/Dockerfile, infra/docker/redis/Dockerfile
=> feat: バッチ処理用のDockerfile作成

api/calc/internal/interface/handler/v1/group.go, api/calc/internal/interface/handler/v1/payment.go
=> fix: レスポンスステータス

api/batch/main.go
=> style: バッチ処理のコード修正

api/user/internal/infrastructure/service/user.go
=> fix: ユーザーエンティティの配列型の値修正

api/calc/config/router.go
=> fix: 支払い完了ステータス更新PATHの修正

api/calc/internal/interface/handler/v1/payment.go
* 支払い完了フラグ更新APIの修正
すまん、ゴミ消したから再度お願いします
=> fix: 支払い完了フラグ更新APIの修正

native/react/package.json, native/react/src/domain/models/auth.ts, native/react/src/domain/models/group.ts, native/react/src/domain/models/groups.ts, native/react/src/domain/models/index.ts, native/react/src/lib/datetime.ts, native/react/src/modules/groups.ts, native/react/src/modules/index.ts, native/react/src/selectors/groups.ts, native/react/src/selectors/index.ts, native/react/yarn.lock
* グループモデルの作成
* 日付フォーマットを統一したいからライブラリ作成
=> feature: グループモデルの作成

native/react/src/domain/models/auth.ts, native/react/src/usecases/auth.ts
=> feat: Tokenのリフレッシュ処理用関数の編集

native/android/app/src/main/java/work/calmato/prestopay/database/DatabaseFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/NationalFlagsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addExpense/AddExpenseFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/BindingUtils.kt, native/android/app/src/main/res/drawable/ic_baseline_menu_24.xml, native/android/app/src/main/res/layout/list_item_country.xml, native/android/app/src/main/res/layout/list_item_tag.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/dimens.xml, native/android/app/src/main/res/values/strings.xml
=> 通貨とタグの表示改善

native/android/app/src/main/java/work/calmato/prestopay/database/DatabaseFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/paymentDetail/PaymentDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterPayment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/BindingUtils.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt, native/android/app/src/main/res/layout/fragment_payment_detail.xml, native/android/app/src/main/res/layout/list_item_payment.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/colors.xml, native/android/app/src/main/res/values/strings.xml
=> Feature android payment complete

native/android/app/build.gradle, native/android/app/src/main/res/layout/list_group_item_plane.xml, native/android/app/src/main/res/layout/list_item_advanced_expense_amount.xml, native/android/app/src/main/res/layout/list_item_advanced_expense_ratio.xml, native/android/app/src/main/res/layout/list_item_checkbox.xml, native/android/app/src/main/res/layout/list_item_grid.xml, native/android/app/src/main/res/layout/list_item_plane.xml, native/android/app/src/main/res/layout/list_item_tag.xml
=> userの新規登録でサムネイル登録を必須に変更した

native/android/app/src/main/res/layout/fragment_account_home.xml, native/android/app/src/main/res/layout/list_item_tag.xml
=> thumbnail表示の修正

docker-compose.yaml
=> fix: docker-compose.yaml

api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/response/group.go, api/calc/internal/domain/group/service.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/interface/handler/v1/group.go, api/calc/mock/domain/group/service.go, api/calc/mock/infrastructure/api/client.go, api/user/config/router.go, docs/12_backend/21_swagger/apiv1.yaml, docs/12_backend/21_swagger/internal.yaml
* グループ非公開設定APIのレスポンス変更
* グループ非公開設定APIのPATH変更
* 変更後のPATHは備考を参照
* #212 の変更対応
=> feature: グループ非公開設定APIの編集

native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupList/GroupListHiddenFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelGroup.kt, native/android/app/src/main/res/layout/fragment_hidden_group_list.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml
=> 非表示グループの削除を実装

native/android/app/src/main/java/work/calmato/prestopay/ui/groupList/GroupListHiddenFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelGroup.kt, native/android/app/src/main/res/drawable/ic_baseline_delete_sweep_24.xml, native/android/app/src/main/res/layout/fragment_hidden_group_list.xml
recycler viewでスライドさせるとリストの一項目を消せるようにした。
=> recycler viewでスライドさせるとリストの一項目を消せるようにした。

native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addPayment/AddPaymentFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/addPayment/AddPaymentStep4Fragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupEdit/GroupEditFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupList/GroupListHiddenFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelAddPayment.kt, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml
- HiddenGroupListからグループ詳細とグループ編集への遷移
- グループ編集での非表示ボタンをはじめからオンに
- TestLabのエラー修正も
=> Feature android navigate from hidden groups to group detail

docker-compose.api.yaml
=> feat: Update docker-compose.yaml

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/GroupsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupFriend/GroupFriendFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml
=> グループと友達の削除の実装

api/calc/internal/application/payment.go, api/calc/internal/application/request/payment.go, api/calc/internal/application/response/payment.go, api/calc/internal/application/validation/payment_test.go, api/calc/internal/interface/handler/v1/payment.go, docs/12_backend/21_swagger/apiv1.yaml
=> feature: 支払い情報APIのリクエスト,レスポンスの変更

api/calc/internal/domain/notification.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/service/group_test.go, api/calc/internal/infrastructure/service/payment.go, api/calc/mock/infrastructure/api/client.go, api/calc/registry/group.go, api/calc/registry/registry.go, api/user/internal/application/response/user.go, api/user/internal/interface/handler/v1/user.go
* グループ追加時のプッシュ通知機能を追加
* グループ編集時のプッシュ通知機能を追加
* グループ招待時のプッシュ通知機能を追加
* 支払い追加時のプッシュ通知機能を追加
* 支払い編集時のプッシュ通知機能を追加
=> feature: プッシュ通知の追加

infra/terraform/env/prod/main.tf, infra/terraform/env/prod/variables.tf
=> feat: 本番用Terraformのテンプレートを作成

api/calc/internal/application/request/payment.go
=> fix: リクエストのバリデーションを削除

native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/settleUp/SettleUpFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelAddPayment.kt, native/android/app/src/main/res/drawable/ic_baseline_arrow_forward_24.xml, native/android/app/src/main/res/layout/fragment_create_group.xml, native/android/app/src/main/res/layout/fragment_settle_up.xml, native/android/app/src/main/res/navigation/navigation.xml, native/android/app/src/main/res/values-ja/strings.xml, native/android/app/src/main/res/values/strings.xml
=> Feature android settle up

api/calc/internal/application/payment.go
* ユーザーごとの合計を、未支払いのみ -> すべて に変更
=> feat: 支払い一覧のレスポンスを編集

native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt
=> fix: OkHTTPの修正

native/android/app/src/main/java/work/calmato/prestopay/database/DatabaseFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiData.kt, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/network/DataTransferObjects.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/FriendsRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/repository/PaymentRepository.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/paymentDetail/PaymentDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/settleUp/SettleUpFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelAddPayment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriend.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelPayment.kt, native/android/app/src/main/res/layout/fragment_group_detail.xml, native/android/app/src/main/res/layout/fragment_settle_up.xml, native/android/app/src/main/res/navigation/navigation.xml
=> Feature android show debt

.github/workflows/cd-batch-api.yaml, .github/workflows/cd-calc-api.yaml, .github/workflows/cd-user-api.yaml, .github/workflows/codeql-analysis.yml, api/calc/internal/application/payment.go, api/calc/internal/application/request/group.go, api/calc/internal/application/request/payment.go, api/calc/internal/application/validation/base.go, api/calc/internal/application/validation/payment_test.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/group.go, api/calc/internal/infrastructure/service/payment.go, api/calc/internal/interface/handler/v1/payment.go, api/calc/lib/common/datetime.go, api/calc/middleware/logging.go, api/calc/mock/infrastructure/api/client.go, api/user/middleware/logging.go, docker-compose.api.stg.yaml, docs/12_backend/01_design/README.md, docs/12_backend/21_swagger/apiv1.yaml
* APIへのリクエスト値のバリデーションをちゃんと設定する
* 支払い一覧APIのレスポンスの修正
* バリデーション については↓のリンク先にまとめたからだいたいあってるか確認して欲しい
* 内容としては、前にwikiにまとめてくれたものベースになってる
* ちょっとAndroidの方で対応してもらうかもしれん部分としては、PaidAt(支払い日時)についてのフォーマットを決めた
> https://github.com/calmato/presto-pay/blob/2ccf07443e848aca48ba457f093ab424d3eea099/docs/12_backend/01_design/README.md
* 支払い一覧APIのレスポンスの修正については、金額がうまく返せてなかったかもだからコード修正してみた
* まだ変な値返ってきそうだったら教えて欲しい
=> feature: APIのバリデーション周りともろもろの編集

infra/server/dev/crontab
=> fix: crontabの設定を変更

api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/validation/user.go
=> style: 変数名のリファクタ

api/calc/internal/infrastructure/service/payment.go, api/calc/internal/infrastructure/service/payment_test.go
* 支払い情報追加/変更時、グループのUpdatedAtも更新するように
=> feat: 支払い情報追加/変更時、グループのUpdatedAtも更新するように

api/calc/internal/application/payment.go
=> fix: 支払い登録時のリクエスト値の絶対値をとるよう制御

api/calc/internal/infrastructure/service/group.go, api/calc/internal/interface/handler/error.go, api/user/internal/interface/handler/error.go
=> refactor: Fluentdへのログ送信をコメントアウト

native/android/app/src/main/java/work/calmato/prestopay/database/Room.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelFriendGroup.kt
=> Fix android create group

api/calc/internal/interface/handler/v1/payment.go
=> feat: 支払い更新APIの修正

docker-compose.api.stg.yaml
=> fix: 検証環境のリソース割合を変更

api/calc/internal/infrastructure/notification/client.go
=> fix: Cloud MassagingでTokenが0,nilのときreturnするように

docker-compose.api.prod.yaml, infra/server/dev/crontab, infra/server/prod/crontab
=> feature: VMのリソース調整等

native/android/app/build.gradle, native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupDetail/GroupDetailFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/settleUpGroup/SettleUpGroupFragment.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterSettleUpChild.kt, native/android/app/src/main/java/work/calmato/prestopay/util/AdapterSettleUpGroup.kt, native/android/app/src/main/java/work/calmato/prestopay/util/BindingUtils.kt, native/android/app/src/main/java/work/calmato/prestopay/util/ViewModelSettleUpGroup.kt, native/android/app/src/main/res/layout/fragment_settle_up_group.xml, native/android/app/src/main/res/layout/list_item_settle_up_child_view.xml, native/android/app/src/main/res/layout/list_item_settle_up_group.xml, native/android/app/src/main/res/navigation/navigation.xml
- グループの貸し借りを精算するために誰が誰に支払うべきかの表示
-支払い精算の一括完了
=> Feature android settleup

api/user/config/router.go, api/user/internal/application/request/user.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/validation/user.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/validation/user.go, api/user/internal/interface/handler/v1/user.go, api/user/mock/application/validation/user.go, api/user/mock/domain/user/repository.go, api/user/mock/domain/user/service.go, docs/12_backend/21_swagger/internal.yaml
=> feature: 認証なしのユーザ作成/編集APIの実装

api/calc/config/router.go, api/calc/internal/application/group.go, api/calc/internal/application/request/group.go, api/calc/internal/application/response/group.go, api/calc/internal/application/validation/group.go, api/calc/internal/domain/user/service.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/user.go, api/calc/internal/interface/handler/v1/group.go, api/calc/mock/application/validation/group.go, api/calc/mock/domain/user/service.go, api/calc/mock/infrastructure/api/client.go, api/user/config/router.go, api/user/internal/application/user.go, docs/12_backend/21_swagger/apiv1.yaml, docs/12_backend/21_swagger/internal.yaml
* 認証機能なしのユーザをグループに追加できるように
* swaggerの更新
* 認証機能を持たないユーザの情報編集用APIの実装
* テスト/デバッグ -> はまだにAndroid実装のときにお願いする
=> feature: 認証機能なしのユーザをグループに追加できるように

docs/12_backend/21_swagger/apiv1.yaml
=> docs: Update swagger

.env.temp, README.md, api/calc/cmd/main.go, api/calc/config/environment.go, api/user/cmd/main.go, api/user/config/environment.go, docker-compose.api.prod.yaml, docker-compose.api.stg.yaml, docker-compose.api.yaml, docker-compose.yaml
=> feature: CloudRunで動かせる用の設定変更

api/calc/cmd/main.go, api/calc/config/environment.go, api/calc/go.mod, api/calc/internal/application/payment.go, api/calc/internal/infrastructure/api/client.go, api/calc/internal/infrastructure/service/exchange.go, api/calc/mock/infrastructure/api/client.go, api/calc/registry/payment.go, api/calc/registry/registry.go, api/user/cmd/main.go, docker-compose.api.prod.yaml, docker-compose.api.stg.yaml, docker-compose.api.yaml
* CloudRunで動かすためのリファクタ
* 環境変数周り
* Redis周り
=> feature: CloudRunで動かすためのリファクタ

.github/workflows/cd-nginx.yaml, docker-compose.nginx.yaml, infra/docker/load-balancer/Dockerfile_development, infra/docker/load-balancer/Dockerfile_staging, infra/nginx/stg/default.conf
=> feature: NginxのDockerfile作成

infra/nginx/stg/default.conf
=> feat: リッスンポートの変更

.github/workflows/cd-nginx.yaml
=> feat: GitHub Actionsの更新

.github/workflows/cd-calc-api-stg.yaml, .github/workflows/cd-nginx-stg.yaml, .github/workflows/cd-user-api-stg.yaml
=> feat: GithubActions内で、CloudRunへデプロイする処理を追加

api/calc/internal/infrastructure/service/payment.go
=> fix: ガード節作ってたけどreturnできてなかったバグの修正

native/android/app/src/main/java/work/calmato/prestopay/network/ApiService.kt, native/android/app/src/main/java/work/calmato/prestopay/ui/groupEdit/GroupEditFragment.kt, native/android/app/src/main/res/layout/fragment_group_edit.xml
=> bugfix: edit fragment fix
